// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ComputeDataHashParams.proto

#ifndef PROTOBUF_INCLUDED_ComputeDataHashParams_2eproto
#define PROTOBUF_INCLUDED_ComputeDataHashParams_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_ComputeDataHashParams_2eproto 

namespace protobuf_ComputeDataHashParams_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_ComputeDataHashParams_2eproto
namespace sotcore {
class ComputeDataHashParams;
class ComputeDataHashParamsDefaultTypeInternal;
extern ComputeDataHashParamsDefaultTypeInternal _ComputeDataHashParams_default_instance_;
}  // namespace sotcore
namespace google {
namespace protobuf {
template<> ::sotcore::ComputeDataHashParams* Arena::CreateMaybeMessage<::sotcore::ComputeDataHashParams>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace sotcore {

// ===================================================================

class ComputeDataHashParams : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sotcore.ComputeDataHashParams) */ {
 public:
  ComputeDataHashParams();
  virtual ~ComputeDataHashParams();

  ComputeDataHashParams(const ComputeDataHashParams& from);

  inline ComputeDataHashParams& operator=(const ComputeDataHashParams& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ComputeDataHashParams(ComputeDataHashParams&& from) noexcept
    : ComputeDataHashParams() {
    *this = ::std::move(from);
  }

  inline ComputeDataHashParams& operator=(ComputeDataHashParams&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ComputeDataHashParams& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ComputeDataHashParams* internal_default_instance() {
    return reinterpret_cast<const ComputeDataHashParams*>(
               &_ComputeDataHashParams_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ComputeDataHashParams* other);
  friend void swap(ComputeDataHashParams& a, ComputeDataHashParams& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ComputeDataHashParams* New() const final {
    return CreateMaybeMessage<ComputeDataHashParams>(NULL);
  }

  ComputeDataHashParams* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ComputeDataHashParams>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ComputeDataHashParams& from);
  void MergeFrom(const ComputeDataHashParams& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ComputeDataHashParams* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string hash = 1;
  void clear_hash();
  static const int kHashFieldNumber = 1;
  const ::std::string& hash() const;
  void set_hash(const ::std::string& value);
  #if LANG_CXX11
  void set_hash(::std::string&& value);
  #endif
  void set_hash(const char* value);
  void set_hash(const char* value, size_t size);
  ::std::string* mutable_hash();
  ::std::string* release_hash();
  void set_allocated_hash(::std::string* hash);

  // bytes data = 2;
  void clear_data();
  static const int kDataFieldNumber = 2;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // uint32 iterations = 3;
  void clear_iterations();
  static const int kIterationsFieldNumber = 3;
  ::google::protobuf::uint32 iterations() const;
  void set_iterations(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:sotcore.ComputeDataHashParams)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr hash_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::uint32 iterations_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ComputeDataHashParams_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ComputeDataHashParams

// string hash = 1;
inline void ComputeDataHashParams::clear_hash() {
  hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ComputeDataHashParams::hash() const {
  // @@protoc_insertion_point(field_get:sotcore.ComputeDataHashParams.hash)
  return hash_.GetNoArena();
}
inline void ComputeDataHashParams::set_hash(const ::std::string& value) {
  
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sotcore.ComputeDataHashParams.hash)
}
#if LANG_CXX11
inline void ComputeDataHashParams::set_hash(::std::string&& value) {
  
  hash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sotcore.ComputeDataHashParams.hash)
}
#endif
inline void ComputeDataHashParams::set_hash(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sotcore.ComputeDataHashParams.hash)
}
inline void ComputeDataHashParams::set_hash(const char* value, size_t size) {
  
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sotcore.ComputeDataHashParams.hash)
}
inline ::std::string* ComputeDataHashParams::mutable_hash() {
  
  // @@protoc_insertion_point(field_mutable:sotcore.ComputeDataHashParams.hash)
  return hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ComputeDataHashParams::release_hash() {
  // @@protoc_insertion_point(field_release:sotcore.ComputeDataHashParams.hash)
  
  return hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ComputeDataHashParams::set_allocated_hash(::std::string* hash) {
  if (hash != NULL) {
    
  } else {
    
  }
  hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hash);
  // @@protoc_insertion_point(field_set_allocated:sotcore.ComputeDataHashParams.hash)
}

// bytes data = 2;
inline void ComputeDataHashParams::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ComputeDataHashParams::data() const {
  // @@protoc_insertion_point(field_get:sotcore.ComputeDataHashParams.data)
  return data_.GetNoArena();
}
inline void ComputeDataHashParams::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sotcore.ComputeDataHashParams.data)
}
#if LANG_CXX11
inline void ComputeDataHashParams::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sotcore.ComputeDataHashParams.data)
}
#endif
inline void ComputeDataHashParams::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sotcore.ComputeDataHashParams.data)
}
inline void ComputeDataHashParams::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sotcore.ComputeDataHashParams.data)
}
inline ::std::string* ComputeDataHashParams::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:sotcore.ComputeDataHashParams.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ComputeDataHashParams::release_data() {
  // @@protoc_insertion_point(field_release:sotcore.ComputeDataHashParams.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ComputeDataHashParams::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:sotcore.ComputeDataHashParams.data)
}

// uint32 iterations = 3;
inline void ComputeDataHashParams::clear_iterations() {
  iterations_ = 0u;
}
inline ::google::protobuf::uint32 ComputeDataHashParams::iterations() const {
  // @@protoc_insertion_point(field_get:sotcore.ComputeDataHashParams.iterations)
  return iterations_;
}
inline void ComputeDataHashParams::set_iterations(::google::protobuf::uint32 value) {
  
  iterations_ = value;
  // @@protoc_insertion_point(field_set:sotcore.ComputeDataHashParams.iterations)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace sotcore

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_ComputeDataHashParams_2eproto
